name = "funyblog"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# 开发环境配置
[dev]
port = 3000

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "funyblog"
database_id = "84acc967-5fe4-4068-86e2-1418618a0b89"

# 静态资源配置
[site]
bucket = "./public"

# 环境变量
[vars]
ENVIRONMENT = "production" 